version: "3"
services:
  backend:
    container_name: wes-backend
    build:
      context: .
      dockerfile: backend.dockerfile
    working_dir: /backend
    environment:
      PYTHONUNBUFFERED: 1
      TZ: Asia/Shanghai
      APP_ENV: test
    volumes:
      - ./backend:/backend
      - ./logs/log:/var/log
    ports:
      - "8800:8000"
    restart: always
    external_links:
      - wes-db-pg
      - wes-db-redis

networks:
  default:
    external: true
    name: wes_network